In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [28]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [29]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [30]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [31]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [32]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [33]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [34]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [35]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [36]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [37]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [38]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [39]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/mnt/d/projects_25/DL-project1/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [41]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

In [42]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=250,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

print("✅ Regression Model training complete!")

Epoch 1/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 99579.8984 - mae: 99579.8984 - val_loss: 98589.9219 - val_mae: 98589.9219
Epoch 2/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100105.3281 - mae: 100105.3281 - val_loss: 97551.3516 - val_mae: 97551.3516
Epoch 3/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99071.4766 - mae: 99071.4766 - val_loss: 94838.2344 - val_mae: 94838.2344
Epoch 4/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95676.7500 - mae: 95676.7500 - val_loss: 90160.8281 - val_mae: 90160.8281
Epoch 5/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89759.3047 - mae: 89759.3047 - val_loss: 83741.4766 - val_mae: 83741.4766
Epoch 6/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 84132.1406 - mae: 84132.1406 - val_loss: 76280.2109 - val_mae: 76280.2109
Epoch 7/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 75745.0625 - mae: 75745.0625 - val_loss: 68853.7812 - val_mae: 68853.7812
Epoch 8/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 67879.2344 - mae: 67879.2344 - val_loss: 62281.8672 - val_mae: 62281.8672
Epoch 9/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62474.1523 - mae: 62474.1523 - val_loss: 57242.3164 - val_mae: 57242.3164
Epoch 10/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56678.1797 - mae: 56678.1797 - val_loss: 53888.2070 - val_mae: 53888.2070
Epoch 11/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54131.2109 - mae: 54131.2109 - val_loss: 52021.4922 - val_mae: 52021.4922
Epoch 12/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52794.4258 - mae: 52794.4258 - val_loss: 51238.6211 - val_mae: 51238.6211
Epoch 13/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51158.5352 - mae: 51158.5352 - val_loss: 50934.6523 - val_mae: 50934.6523
Epoch 14/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50050.3125 - mae: 50050.3125 - val_loss: 50804.7695 - val_mae: 50804.7695
Epoch 15/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50249.7656 - mae: 50249.7656 - val_loss: 50735.4609 - val_mae: 50735.4609
Epoch 16/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50772.1328 - mae: 50772.1328 - val_loss: 50679.1680 - val_mae: 50679.1680
Epoch 17/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49823.4414 - mae: 49823.4414 - val_loss: 50645.4414 - val_mae: 50645.4414
Epoch 18/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50457.6367 - mae: 50457.6367 - val_loss: 50619.7656 - val_mae: 50619.7656
Epoch 19/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50100.3008 - mae: 50100.3008 - val_loss: 50586.0273 - val_mae: 50586.0273
Epoch 20/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49848.1953 - mae: 49848.1953 - val_loss: 50555.3047 - val_mae: 50555.3047
Epoch 21/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50349.6562 - mae: 50349.6562 - val_loss: 50539.2031 - val_mae: 50539.2031
Epoch 22/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49674.5469 - mae: 49674.5469 - val_loss: 50508.8516 - val_mae: 50508.8516
Epoch 23/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50007.7695 - mae: 50007.7695 - val_loss: 50491.0508 - val_mae: 50491.0508
Epoch 24/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49414.7930 - mae: 49414.7930 - val_loss: 50477.8555 - val_mae: 50477.8555
Epoch 25/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49744.1602 - mae: 49744.1602 - val_loss: 50457.2656 - val_mae: 50457.2656
Epoch 26/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49499.6250 - mae: 49499.6250 - val_loss: 50439.9883 - val_mae: 50439.9883
Epoch 27/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50214.3789 - mae: 50214.3789 - val_loss: 50424.9453 - val_mae: 50424.9453
Epoch 28/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50215.4727 - mae: 50215.4727 - val_loss: 50414.0859 - val_mae: 50414.0859
Epoch 29/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49924.6133 - mae: 49924.6133 - val_loss: 50395.2461 - val_mae: 50395.2461
Epoch 30/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50063.6523 - mae: 50063.6523 - val_loss: 50387.7461 - val_mae: 50387.7461
Epoch 31/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49817.7227 - mae: 49817.7227 - val_loss: 50374.3125 - val_mae: 50374.3125
Epoch 32/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49994.8906 - mae: 49994.8906 - val_loss: 50358.5000 - val_mae: 50358.5000
Epoch 33/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49943.6953 - mae: 49943.6953 - val_loss: 50346.9883 - val_mae: 50346.9883
Epoch 34/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49218.5000 - mae: 49218.5000 - val_loss: 50339.7344 - val_mae: 50339.7344
Epoch 35/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49710.1680 - mae: 49710.1680 - val_loss: 50338.1055 - val_mae: 50338.1055
Epoch 36/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49702.6719 - mae: 49702.6719 - val_loss: 50330.4102 - val_mae: 50330.4102
Epoch 37/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49545.8203 - mae: 49545.8203 - val_loss: 50330.8008 - val_mae: 50330.8008
Epoch 38/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50148.9688 - mae: 50148.9688 - val_loss: 50315.9336 - val_mae: 50315.9336
Epoch 39/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49954.8047 - mae: 49954.8047 - val_loss: 50312.7422 - val_mae: 50312.7422
Epoch 40/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49873.6250 - mae: 49873.6250 - val_loss: 50309.9219 - val_mae: 50309.9219
Epoch 41/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49559.3008 - mae: 49559.3008 - val_loss: 50299.8945 - val_mae: 50299.8945
Epoch 42/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49669.5625 - mae: 49669.5625 - val_loss: 50304.0234 - val_mae: 50304.0234
Epoch 43/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49318.4062 - mae: 49318.4062 - val_loss: 50296.6406 - val_mae: 50296.6406
Epoch 44/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49508.7617 - mae: 49508.7617 - val_loss: 50287.0469 - val_mae: 50287.0469
Epoch 45/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49485.4180 - mae: 49485.4180 - val_loss: 50294.1016 - val_mae: 50294.1016
Epoch 46/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49624.3555 - mae: 49624.3555 - val_loss: 50280.8750 - val_mae: 50280.8750
Epoch 47/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49934.5273 - mae: 49934.5273 - val_loss: 50282.5508 - val_mae: 50282.5508
Epoch 48/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49396.8555 - mae: 49396.8555 - val_loss: 50279.4414 - val_mae: 50279.4414
Epoch 49/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49187.2578 - mae: 49187.2578 - val_loss: 50278.9766 - val_mae: 50278.9766
Epoch 50/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49705.5430 - mae: 49705.5430 - val_loss: 50268.7266 - val_mae: 50268.7266
Epoch 51/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49277.1602 - mae: 49277.1602 - val_loss: 50268.5664 - val_mae: 50268.5664
Epoch 52/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50138.9922 - mae: 50138.9922 - val_loss: 50270.4062 - val_mae: 50270.4062
Epoch 53/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49534.1445 - mae: 49534.1445 - val_loss: 50259.1445 - val_mae: 50259.1445
Epoch 54/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50083.1289 - mae: 50083.1289 - val_loss: 50266.2383 - val_mae: 50266.2383
Epoch 55/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49316.7617 - mae: 49316.7617 - val_loss: 50257.8711 - val_mae: 50257.8711
Epoch 56/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49480.7188 - mae: 49480.7188 - val_loss: 50264.3164 - val_mae: 50264.3164
Epoch 57/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49370.9688 - mae: 49370.9688 - val_loss: 50263.8633 - val_mae: 50263.8633
Epoch 58/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50048.5078 - mae: 50048.5078 - val_loss: 50267.3359 - val_mae: 50267.3359
Epoch 59/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49711.5898 - mae: 49711.5898 - val_loss: 50262.1680 - val_mae: 50262.1680
Epoch 60/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49457.9805 - mae: 49457.9805 - val_loss: 50265.4883 - val_mae: 50265.4883
Epoch 61/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49699.6367 - mae: 49699.6367 - val_loss: 50266.2539 - val_mae: 50266.2539
Epoch 62/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49904.9531 - mae: 49904.9531 - val_loss: 50258.0664 - val_mae: 50258.0664
Epoch 63/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49508.9805 - mae: 49508.9805 - val_loss: 50252.2109 - val_mae: 50252.2109
Epoch 64/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49207.9766 - mae: 49207.9766 - val_loss: 50260.2305 - val_mae: 50260.2305
Epoch 65/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49298.9375 - mae: 49298.9375 - val_loss: 50261.1484 - val_mae: 50261.1484
Epoch 66/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49284.1328 - mae: 49284.1328 - val_loss: 50267.1211 - val_mae: 50267.1211
Epoch 67/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49470.8203 - mae: 49470.8203 - val_loss: 50272.2109 - val_mae: 50272.2109
Epoch 68/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49530.1016 - mae: 49530.1016 - val_loss: 50278.9023 - val_mae: 50278.9023
Epoch 69/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48932.3750 - mae: 48932.3750 - val_loss: 50278.0391 - val_mae: 50278.0391
Epoch 70/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48936.4141 - mae: 48936.4141 - val_loss: 50279.7852 - val_mae: 50279.7852
Epoch 71/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48924.8789 - mae: 48924.8789 - val_loss: 50282.5977 - val_mae: 50282.5977
Epoch 72/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49654.0469 - mae: 49654.0469 - val_loss: 50279.7305 - val_mae: 50279.7305
Epoch 73/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49480.2383 - mae: 49480.2383 - val_loss: 50276.9961 - val_mae: 50276.9961
Epoch 74/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49548.0742 - mae: 49548.0742 - val_loss: 50279.7578 - val_mae: 50279.7578
Epoch 75/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49102.0938 - mae: 49102.0938 - val_loss: 50286.8203 - val_mae: 50286.8203
Epoch 76/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49090.1484 - mae: 49090.1484 - val_loss: 50277.2773 - val_mae: 50277.2773
Epoch 77/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49201.9609 - mae: 49201.9609 - val_loss: 50279.5859 - val_mae: 50279.5859
Epoch 78/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49122.4180 - mae: 49122.4180 - val_loss: 50286.8398 - val_mae: 50286.8398
✅ Regression Model training complete!

In [45]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [46]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 78456), started 0:02:59 ago. (Use '!kill 78456' to kill it.)

In [47]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51085.2812 - mae: 51085.2812
Test MAE : 50252.2109375

In [48]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.